# Generated by Django 6.1 on 2026-08-25 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_alter_servicio_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del cliente', max_length=255)),
                ('apellido', models.CharField(help_text='Apellido del cliente', max_length=255)),
                ('activo', models.BooleanField(default=True, help_text='Indica si el cliente está activo')),
            ],
        ),
    ]
