# Generated by Django 6.1 on 2026-09-01 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del coordinador', max_length=255)),
                ('apellido', models.CharField(help_text='Apellido del coordinador', max_length=255)),
                ('numero_documento', models.IntegerField(help_text='Número de documento del coordinador', unique=True)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de alta en el sistema')),
                ('activo', models.BooleanField(default=True, help_text='Indica si el coordinador está activo')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del empleado', max_length=255)),
                ('apellido', models.CharField(help_text='Apellido del empleado', max_length=255)),
                ('numero_legajo', models.IntegerField(help_text='Número de legajo único del empleado', unique=True)),
                ('activo', models.BooleanField(default=True, help_text='Indica si el empleado está activo')),
            ],
        ),
        migrations.CreateModel(
            name='ReservaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se realizó la reserva')),
                ('fecha_servicio', models.DateField(help_text='Fecha solicitada para el evento/servicio')),
                ('cliente', models.ForeignKey(help_text='Cliente que realiza la reserva', on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='servicios.cliente')),
                ('coordinador', models.ForeignKey(help_text='Coordinador responsable de la reserva', on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='servicios.coordinador')),
                ('empleado', models.ForeignKey(help_text='Empleado asignado a la reserva', on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='servicios.empleado')),
                ('servicio', models.ForeignKey(help_text='Servicio reservado', on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='servicios.servicio')),
            ],
        ),
    ]
