# Generated by Django 6.1 on 2026-09-03 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0004_coordinador_empleado_reservaservicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservaservicio',
            name='servicio',
        ),
        migrations.AddField(
            model_name='reservaservicio',
            name='servicios',
            field=models.ManyToManyField(help_text='Servicios incluidos en la reserva', related_name='reservas', to='servicios.servicio'),
        ),
        migrations.AlterField(
            model_name='reservaservicio',
            name='empleado',
            field=models.ForeignKey(help_text='Empleado que toma la reserva', on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='servicios.empleado'),
        ),
    ]
